services:
  - type: web
    name: chat-backend
    runtime: java
    plan: free
    buildCommand: chmod +x ./mvnw && ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/chat-backend-0.0.1-SNAPSHOT.jar
    healthCheckPath: /
    env: production
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=90.0
      - key: DATABASE_URL
        fromDatabase:
          name: chat-db
          property: connectionString
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: chat-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: chat-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: chat-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: production

databases:
  - name: chat-db
    databaseName: chatapp
    user: chatapp
    plan: free
